version: '2'

services:
  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup
    restart: unless-stopped
    ports:
      - 55414:55414/tcp
      - 55413:55413/tcp
      - 55415:55415/tcp
      - 35623:35623/udp
    environment:
      - PUID=1000 # Enter the UID of the user who should own the files here
      - PGID=100  # Enter the GID of the user who should own the files here
      - TZ=Europe/Tallinn # Enter your timezone
    volumes:
      - urbackup-database:/var/urbackup:Z
      - /data/backups/urbackup:/backups
      # Uncomment the next line if you want to bind-mount the www-folder
      #- /path/to/wwwfolder:/usr/share/urbackup
    network: "host"
    # Uncomment the following two lines if you're using BTRFS support
    #cap_add:
    #  - SYS_ADMIN
    # Uncomment the following two lines if you're using ZFS support
    devices:
      - /dev/zfs:/dev/zfs
  
volumes:
  urbackup-database:
    name: urbackup-database
