version: "3"
services:
  homeassistant:
    ports:
      - 8123:8123
    labels:
      - "io.containers.autoupdate=registry"
        #- "PODMAN_SYSTEMD_UNIT=container-homeassitant.service"
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: True
    network: host
